"""
Plot Gallery Generator
Automatically generates a static HTML gallery of all plots in the /plots directory.
"""

import json
from pathlib import Path

gallery_path = Path("gallery.html")
plots_dir = Path("plots")

html_header = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yellorn Plot Gallery</title>
    <style>
        body { font-family: sans-serif; background: #181825; color: #fff; margin: 0; padding: 0; }
        .gallery { display: flex; flex-wrap: wrap; gap: 2rem; padding: 2rem; justify-content: center; }
        .plot-card { background: #232347; border-radius: 1rem; box-shadow: 0 2px 8px #0004; padding: 1.5rem; width: 320px; }
        .plot-title { font-size: 1.3rem; font-weight: bold; margin-bottom: 0.5rem; }
        .plot-meta { font-size: 0.95rem; color: #b3b3cc; margin-bottom: 0.5rem; }
        .plot-desc { margin-bottom: 0.5rem; }
        .plot-coords, .plot-size { font-size: 0.9rem; color: #a0a0b0; }
        .agent-id { font-size: 0.9rem; color: #7ee787; }
    </style>
</head>
<body>
    <h1 style="text-align:center; margin-top:2rem;">Yellorn Plot Gallery</h1>
    <div class="gallery">
"""

html_footer = """
    </div>
    <footer style="text-align:center; color:#888; margin:2rem 0;">Generated by Yellorn Copilot</footer>
</body>
</html>
"""

plot_cards = []

for plot_file in plots_dir.glob("*.json"):
    try:
        with open(plot_file) as f:
            plot = json.load(f)
        card = f"""
        <div class='plot-card'>
            <div class='plot-title'>{plot.get('name', plot_file.stem)}</div>
            <div class='plot-meta'>File: {plot_file.name}</div>
            <div class='plot-desc'>{plot.get('description', '')}</div>
            <div class='agent-id'>Agent ID: {plot.get('agent_id', 'N/A')}</div>
            <div class='plot-coords'>Coordinates: {plot.get('coordinates', {})}</div>
            <div class='plot-size'>Size: {plot.get('size', {})}</div>
        </div>
        """
        plot_cards.append(card)
    except Exception as e:
        plot_cards.append(
            f"<div class='plot-card'><b>Error loading {plot_file.name}:</b> {e}</div>"
        )

with open(gallery_path, "w") as f:
    f.write(html_header)
    f.write("\n".join(plot_cards))
    f.write(html_footer)

print(f"✅ Plot gallery generated: {gallery_path}")
